/* Generated by cbindgen. Do not edit manually. */


#ifndef COPYLOCKER_H
#define COPYLOCKER_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operation completed successfully.
 */
#define CL_SUCCESS 0

/**
 * Operation failed; inspect `cl_error.code` for the stable numeric category.
 */
#define CL_FAILURE -1

/**
 * Invalid or destroyed client handle.
 */
#define CL_STATE_ERROR -1

/**
 * No credential is installed.
 */
#define CL_STATE_UNLICENSED 0

/**
 * Activation is in progress.
 */
#define CL_STATE_ACTIVATING 1

/**
 * The credential is current.
 */
#define CL_STATE_ACTIVE 2

/**
 * An online refresh is due.
 */
#define CL_STATE_NEEDS_REVALIDATION 3

/**
 * A transient outage is inside grace.
 */
#define CL_STATE_GRACE 4

/**
 * Productive key derivation is unavailable pending recovery.
 */
#define CL_STATE_LOCKED 5

/**
 * The credential was revoked and wiped.
 */
#define CL_STATE_REVOKED 6

/**
 * Integrity verification failed closed.
 */
#define CL_STATE_TAMPERED 7

/**
 * Opaque process-local client handle. Never dereference this pointer.
 */
typedef struct cl_client cl_client;

/**
 * Borrowed length-delimited UTF-8 string. A trailing NUL is neither required nor included.
 */
typedef struct cl_str {
  const char *data;
  size_t len;
} cl_str;

/**
 * Borrowed byte slice. The caller retains ownership for the duration of the call.
 */
typedef struct cl_bytes {
  const uint8_t *data;
  size_t len;
} cl_bytes;

/**
 * Build-time client configuration. All borrowed fields are copied by `cl_create`.
 */
typedef struct cl_config {
  struct cl_str server_url;
  struct cl_str app_id;
  struct cl_str product_id;
  struct cl_str app_version;
  struct cl_str release_id;
  struct cl_str build_fingerprint;
  struct cl_bytes current_root_key;
  /**
   * Empty when no successor Root key is pre-positioned.
   */
  struct cl_bytes next_root_key;
  struct cl_bytes fingerprint_salt;
  uint64_t variant_id;
  /**
   * Exactly 32 bytes.
   */
  struct cl_bytes variant_const;
  /**
   * Exactly 32 bytes and registered with the release evidence.
   */
  struct cl_bytes module_digest;
  /**
   * Must be 0 or 1.
   */
  uint8_t allow_unbound_olk;
  /**
   * Must be 0 or 1; permits HTTP only for loopback development origins.
   */
  uint8_t allow_insecure_localhost;
} cl_config;

/**
 * Stable detail-free error returned across the host boundary.
 */
typedef struct cl_error {
  uint32_t code;
} cl_error;

/**
 * Owned output buffer. Release it with `cl_free_buf` exactly once when practical.
 * Repeated releases of the same unchanged value are tolerated.
 */
typedef struct cl_buf {
  uint8_t *data;
  size_t len;
  /**
   * Opaque allocation token; callers must not modify it.
   */
  size_t handle;
} cl_buf;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create and restore a client. Returns NULL on failure.
 *
 * # Safety
 * `config` and every non-empty borrowed field must point to readable memory for the duration of
 * this call. `error`, when non-NULL, must point to writable `cl_error` storage.
 */
struct cl_client *cl_create(const struct cl_config *config, struct cl_error *error);

/**
 * Destroy a client handle. NULL, invalid, and repeated destroys are no-ops.
 */
void cl_destroy(struct cl_client *client);

/**
 * Activate with a license key.
 *
 * # Safety
 * Non-empty input fields must point to readable memory. `error`, when non-NULL, must be writable.
 */
int32_t cl_activate(struct cl_client *client, struct cl_str key, struct cl_error *error);

/**
 * Release an online seat or erase a local OLK.
 *
 * # Safety
 * `error`, when non-NULL, must point to writable `cl_error` storage.
 */
int32_t cl_deactivate(struct cl_client *client, struct cl_error *error);

/**
 * Return the advisory UI state, or `CL_STATE_ERROR` for an invalid handle or panic.
 */
int32_t cl_state(struct cl_client *client);

/**
 * Authenticate and decrypt a sealed asset.
 *
 * # Safety
 * Non-empty input fields must point to readable memory. `error`, when non-NULL, must be writable.
 */
struct cl_buf cl_unseal(struct cl_client *client,
                        struct cl_str feature,
                        struct cl_bytes data,
                        struct cl_error *error);

/**
 * Answer an opaque canonical-CBOR feature challenge.
 *
 * # Safety
 * Non-empty input fields must point to readable memory. `error`, when non-NULL, must be writable.
 */
struct cl_buf cl_challenge(struct cl_client *client, struct cl_bytes input, struct cl_error *error);

/**
 * Create and persist a device-bound offline activation request.
 *
 * # Safety
 * Non-empty input fields must point to readable memory. `error`, when non-NULL, must be writable.
 */
struct cl_buf cl_offline_request(struct cl_client *client,
                                 struct cl_str key,
                                 struct cl_error *error);

/**
 * Verify and install an offline activation response.
 *
 * # Safety
 * Non-empty input fields must point to readable memory. `error`, when non-NULL, must be writable.
 */
int32_t cl_offline_import(struct cl_client *client, struct cl_bytes data, struct cl_error *error);

/**
 * Verify and install an armored Offline License Key bundle.
 *
 * # Safety
 * Non-empty input fields must point to readable memory. `error`, when non-NULL, must be writable.
 */
int32_t cl_import_olk(struct cl_client *client, struct cl_str data, struct cl_error *error);

/**
 * Release a buffer returned by this library. Repeated releases are no-ops.
 */
void cl_free_buf(struct cl_buf buffer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* COPYLOCKER_H */
