import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const exampleDirectory = resolve(scriptDirectory, '..')
const vectorPath = resolve(exampleDirectory, '../../vectors/CL-STD-1/kat.json')
const outputPath = resolve(exampleDirectory, 'src/main/generated-config.ts')

const vector = JSON.parse(await readFile(vectorPath, 'utf8'))
const rootKeyHex = vector?.signatures?.[0]?.verifying_key
requireHex(rootKeyHex, undefined, 'KAT Root verifying key')

const serverUrl = process.env.CL_EXAMPLE_SERVER_URL ?? 'http://127.0.0.1:8787/'
const parsedServerUrl = new URL(serverUrl)
const localhost = ['127.0.0.1', '[::1]', 'localhost'].includes(parsedServerUrl.hostname)
const allowInsecureLocalhost = parsedServerUrl.protocol === 'http:' && localhost
if (parsedServerUrl.protocol !== 'https:' && !allowInsecureLocalhost) {
  throw new Error('CL_EXAMPLE_SERVER_URL must use HTTPS or loopback HTTP')
}

const expectedModuleDigestHex =
  process.env.CL_EXAMPLE_MODULE_DIGEST ?? '43'.repeat(32)
requireHex(expectedModuleDigestHex, 32, 'embedded module digest')

const config = {
  serverUrl,
  appId: 'dev.copylocker.example.electron',
  productId: process.env.CL_EXAMPLE_PRODUCT_ID ?? 'kat-product',
  appVersion: '0.1.0',
  releaseId: process.env.CL_EXAMPLE_RELEASE_ID ?? 'desktop-example',
  buildFingerprint:
    process.env.CL_EXAMPLE_BUILD_FINGERPRINT ?? 'desktop-example-dev',
  currentRootKeyHex: rootKeyHex,
  fingerprintSaltHex: Buffer.from(
    'copylocker-desktop-example-fingerprint-salt',
    'utf8',
  ).toString('hex'),
  variantId: 1,
  variantConstHex: '43'.repeat(32),
  expectedModuleDigestHex,
  allowInsecureLocalhost,
}

const generated = `// Generated by scripts/generate-config.mjs. Do not edit.\n` +
  `export const COPYLOCKER_BUILD_CONFIG = ${JSON.stringify(config, null, 2)} as const\n`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, generated, 'utf8')

function requireHex(value, expectedBytes, field) {
  if (
    typeof value !== 'string' ||
    value.length === 0 ||
    value.length % 2 !== 0 ||
    !/^[0-9a-f]+$/i.test(value) ||
    (expectedBytes !== undefined && value.length !== expectedBytes * 2)
  ) {
    throw new Error(`Invalid ${field}`)
  }
}
