//! Known-answer test vectors (`crypto-architecture.md §9`).
//!
//! Vectors serve two purposes that the conformance harness cannot:
//!
//! - **Cross-target agreement.** The same vector file is replayed on native, on
//!   `wasm32-unknown-unknown` in the browser, and inside the Cloudflare Worker. A suite that
//!   passes the harness on each target independently could still disagree between them.
//! - **Cross-version agreement.** A vector generated by v0.1 must still verify under v0.9, or a
//!   credential issued last year stops working.
//!
//! Because both signature components are deterministic, positive vectors can pin the exact
//! expected signature bytes rather than merely asserting "it verifies".

use alloc::string::String;
use alloc::vec::Vec;

use copylocker_proto::keywrap::{
    credential_wrap_key, CredentialSealContext, KekWrapContext, KekWrapKind, CREDENTIAL_WRAP_SALT,
};
use copylocker_suite::{
    AeadScheme, Ciphertext, CryptoSuite, DomainCtx, KeyEncapsulation, SharedSecret, Signature,
    SignatureScheme,
};
use copylocker_types::{ArtifactKind, EpochId, Fingerprint, LicenseId, MachineId};
use serde::{Deserialize, Serialize};

/// A vector file for one suite.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct VectorFile {
    /// Suite identifier as `0x`-prefixed hex, e.g. `0x01000001`.
    pub suite_id: String,
    /// Human-readable suite name.
    pub suite_name: String,
    /// Vector format version, so a future format change is detectable.
    pub format: u32,
    /// Signature vectors.
    #[serde(default)]
    pub signatures: Vec<SignatureVector>,
    /// Key-encapsulation vectors.
    #[serde(default)]
    pub kem: Vec<KemVector>,
    /// Authenticated-encryption vectors.
    #[serde(default)]
    pub aead: Vec<AeadVector>,
    /// Key-derivation vectors.
    #[serde(default)]
    pub kdf: Vec<KdfVector>,
    /// Fingerprint vectors.
    #[serde(default)]
    pub fingerprints: Vec<FingerprintVector>,
    /// Canonical protocol artifact encodings.
    #[serde(default)]
    pub artifacts: Vec<ArtifactVector>,
    /// Root-to-epoch-to-artifact certificate-chain vectors.
    #[serde(default)]
    pub chains: Vec<ChainVector>,
}

/// One signature vector.
///
/// `expect_valid = false` marks a **negative** vector: input that must be rejected. The spec
/// requires negative coverage for single-component forgery, cross-domain replay, and tampered
/// messages. Protocol-level negative cases live in the other vector groups.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct SignatureVector {
    /// What this vector exercises.
    pub name: String,
    /// Hex-encoded signing key.
    pub signing_key: String,
    /// Hex-encoded verifying key.
    pub verifying_key: String,
    /// Artifact kind naming the domain used when signing.
    pub sign_kind: String,
    /// Artifact kind used when verifying; differs from `sign_kind` in replay vectors.
    pub verify_kind: String,
    /// Product identifier used when signing.
    pub sign_product: String,
    /// Product identifier used when verifying.
    pub verify_product: String,
    /// Hex-encoded message.
    pub message: String,
    /// Hex-encoded signature. For negative vectors this may be a deliberately corrupted value.
    pub signature: String,
    /// Whether verification must succeed.
    pub expect_valid: bool,
}

/// One key-encapsulation vector.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct KemVector {
    /// What this vector exercises.
    pub name: String,
    /// Hex-encoded decapsulation key.
    pub decapsulation_key: String,
    /// Hex-encoded encapsulation key derived from `decapsulation_key`.
    pub encapsulation_key: String,
    /// Hex-encoded encapsulation ciphertext.
    pub ciphertext: String,
    /// Hex-encoded reference shared secret.
    pub shared_secret: String,
    /// Whether decapsulation must recover the reference secret.
    pub expect_valid: bool,
}

/// One authenticated-encryption vector.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct AeadVector {
    /// What this vector exercises.
    pub name: String,
    /// Hex-encoded key.
    pub key: String,
    /// Hex-encoded nonce.
    pub nonce: String,
    /// Hex-encoded associated data.
    pub aad: String,
    /// Hex-encoded plaintext.
    pub plaintext: String,
    /// Hex-encoded ciphertext and authentication tag.
    pub ciphertext: String,
    /// Whether opening must recover the plaintext.
    pub expect_valid: bool,
}

/// One KDF vector.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct KdfVector {
    /// What this vector exercises.
    pub name: String,
    /// Hex-encoded salt.
    pub salt: String,
    /// Hex-encoded input key material.
    pub ikm: String,
    /// Hex-encoded info parts.
    pub info: Vec<String>,
    /// Hex-encoded expected 32-byte output.
    pub expect: String,
}

/// One fingerprint vector.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct FingerprintVector {
    /// What this vector exercises.
    pub name: String,
    /// Hex-encoded vendor salt.
    pub salt: String,
    /// Attributes as `key = [tag, payload]`, matching the canonical encoding.
    pub attrs: Vec<(String, AttrSpec)>,
    /// Hex-encoded expected digest.
    pub expect: String,
}

/// One canonical protocol-artifact encoding.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct ArtifactVector {
    /// What this vector exercises.
    pub name: String,
    /// Artifact domain name.
    pub kind: String,
    /// Hex-encoded canonical CBOR body.
    pub canonical: String,
}

/// One complete Root -> Epoch -> artifact verification chain.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct ChainVector {
    /// What this vector exercises.
    pub name: String,
    /// Product identifier used by both signatures.
    pub product_id: String,
    /// Hex-encoded root verifying key.
    pub root_verifying_key: String,
    /// Hex-encoded digest pinned by the client.
    pub pinned_root_digest: String,
    /// Hex-encoded canonical epoch-certificate envelope.
    pub epoch_envelope: String,
    /// Artifact kind contained in `artifact_envelope`.
    pub artifact_kind: String,
    /// Hex-encoded canonical artifact envelope.
    pub artifact_envelope: String,
    /// Verification time.
    pub now: i64,
    /// Whether the whole chain must verify.
    pub expect_valid: bool,
}

/// Attribute value in vector form.
#[derive(Clone, Serialize, Deserialize, Debug)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AttrSpec {
    /// Explicitly absent.
    Absent,
    /// A normalised string.
    Text {
        /// The value.
        value: String,
    },
    /// A normalised set.
    Set {
        /// The members.
        values: Vec<String>,
    },
    /// An integer.
    Int {
        /// The value.
        value: i64,
    },
}

impl AttrSpec {
    /// Convert to the runtime attribute type, applying normalisation.
    #[must_use]
    pub fn to_attr(&self) -> copylocker_suite::device::AttrValue {
        use copylocker_suite::device::AttrValue;
        match self {
            Self::Absent => AttrValue::Absent,
            Self::Text { value } => AttrValue::text(value),
            Self::Set { values } => AttrValue::set(values.iter()),
            Self::Int { value } => AttrValue::Int(*value),
        }
    }
}

/// Failure while replaying a vector.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum KatError {
    /// A hex field would not decode.
    BadHex(String),
    /// An artifact kind name was not recognised.
    UnknownKind(String),
    /// A key would not decode.
    BadKey(String),
    /// The suite in the file does not match the suite under test.
    SuiteMismatch {
        /// What the file declares.
        expected: String,
        /// What the suite under test declares.
        actual: String,
    },
    /// A vector's outcome differed from what it declares.
    Mismatch {
        /// Vector name.
        name: String,
        /// Explanation.
        detail: String,
    },
}

impl core::fmt::Display for KatError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::BadHex(s) => write!(f, "malformed hex in {s}"),
            Self::UnknownKind(s) => write!(f, "unknown artifact kind {s}"),
            Self::BadKey(s) => write!(f, "malformed key in {s}"),
            Self::SuiteMismatch { expected, actual } => {
                write!(f, "vector file is for suite {expected}, not {actual}")
            }
            Self::Mismatch { name, detail } => write!(f, "vector {name}: {detail}"),
        }
    }
}

/// Map an artifact kind's context name back to the enum.
fn kind_by_name(name: &str) -> Option<ArtifactKind> {
    ArtifactKind::ALL.into_iter().find(|k| k.ctx_name() == name)
}

fn unhex(field: &str, value: &str) -> Result<Vec<u8>, KatError> {
    hex::decode(value).map_err(|_| KatError::BadHex(String::from(field)))
}

/// Replay every vector in a file against a suite.
///
/// # Errors
///
/// Returns the first vector whose outcome disagrees with its declaration.
pub fn replay<S: CryptoSuite>(file: &VectorFile) -> Result<usize, KatError> {
    let expected = alloc::format!("{}", S::SUITE_ID);
    if !file.suite_id.eq_ignore_ascii_case(&expected) {
        return Err(KatError::SuiteMismatch {
            expected: file.suite_id.clone(),
            actual: expected,
        });
    }

    let mut run = 0;
    for v in &file.signatures {
        replay_signature::<S>(v)?;
        run += 1;
    }
    for v in &file.kem {
        replay_kem::<S>(v)?;
        run += 1;
    }
    for v in &file.aead {
        replay_aead::<S>(v)?;
        run += 1;
    }
    for v in &file.kdf {
        replay_kdf::<S>(v)?;
        run += 1;
    }
    for v in &file.fingerprints {
        replay_fingerprint::<S>(v)?;
        run += 1;
    }
    for v in &file.artifacts {
        crate::protocol_kat::replay_artifact(v)?;
        run += 1;
    }
    for v in &file.chains {
        crate::protocol_kat::replay_chain::<S>(v)?;
        run += 1;
    }
    Ok(run)
}

fn replay_kem<S: CryptoSuite>(v: &KemVector) -> Result<(), KatError> {
    type Kem<S> = <S as CryptoSuite>::Kem;

    let dk = Kem::<S>::decode_dk(&unhex(&v.name, &v.decapsulation_key)?)
        .map_err(|_| KatError::BadKey(v.name.clone()))?;
    let ek = Kem::<S>::decode_ek(&unhex(&v.name, &v.encapsulation_key)?)
        .map_err(|_| KatError::BadKey(v.name.clone()))?;
    if Kem::<S>::encap_key(&dk) != ek {
        return Err(KatError::Mismatch {
            name: v.name.clone(),
            detail: String::from("encapsulation key does not derive from decapsulation key"),
        });
    }

    let ct = Ciphertext(unhex(&v.name, &v.ciphertext)?);
    let expected = unhex(&v.name, &v.shared_secret)?;
    let recovered = Kem::<S>::decap(&dk, &ct)
        .ok()
        .map(|secret| secret.expose().to_vec());
    let valid = recovered.as_deref() == Some(expected.as_slice());
    if valid != v.expect_valid {
        return Err(KatError::Mismatch {
            name: v.name.clone(),
            detail: if v.expect_valid {
                String::from("decapsulation did not recover the reference secret")
            } else {
                String::from("invalid encapsulation recovered the reference secret")
            },
        });
    }
    Ok(())
}

fn replay_aead<S: CryptoSuite>(v: &AeadVector) -> Result<(), KatError> {
    type Aead<S> = <S as CryptoSuite>::Aead;

    let key = unhex(&v.name, &v.key)?;
    let nonce = unhex(&v.name, &v.nonce)?;
    let aad = unhex(&v.name, &v.aad)?;
    let plaintext = unhex(&v.name, &v.plaintext)?;
    let ciphertext = unhex(&v.name, &v.ciphertext)?;
    let opened = Aead::<S>::open(&key, &nonce, &aad, &ciphertext).ok();
    let valid = opened.as_deref() == Some(plaintext.as_slice());
    if valid != v.expect_valid {
        return Err(KatError::Mismatch {
            name: v.name.clone(),
            detail: if v.expect_valid {
                String::from("authenticated decryption did not recover the plaintext")
            } else {
                String::from("invalid authenticated ciphertext was accepted")
            },
        });
    }
    if v.expect_valid {
        let regenerated =
            Aead::<S>::seal(&key, &nonce, &aad, &plaintext).map_err(|_| KatError::Mismatch {
                name: v.name.clone(),
                detail: String::from("re-encryption failed"),
            })?;
        if regenerated != ciphertext {
            return Err(KatError::Mismatch {
                name: v.name.clone(),
                detail: String::from("re-encryption produced different bytes"),
            });
        }
    }
    Ok(())
}

fn replay_signature<S: CryptoSuite>(v: &SignatureVector) -> Result<(), KatError> {
    type Sig<S> = <S as CryptoSuite>::Sig;

    let vk_bytes = unhex(&v.name, &v.verifying_key)?;
    let vk = Sig::<S>::decode_vk(&vk_bytes).map_err(|_| KatError::BadKey(v.name.clone()))?;
    let msg = unhex(&v.name, &v.message)?;
    let sig = Signature(unhex(&v.name, &v.signature)?);

    let verify_kind =
        kind_by_name(&v.verify_kind).ok_or_else(|| KatError::UnknownKind(v.verify_kind.clone()))?;
    let ctx = DomainCtx::new(verify_kind, S::SUITE_ID, &v.verify_product);
    let ok = Sig::<S>::verify(&vk, ctx, &msg, &sig).is_ok();

    if ok != v.expect_valid {
        return Err(KatError::Mismatch {
            name: v.name.clone(),
            detail: if v.expect_valid {
                String::from("expected the signature to verify, but it did not")
            } else {
                String::from("expected the signature to be rejected, but it verified")
            },
        });
    }

    // For positive vectors, also confirm that re-signing reproduces the exact bytes. This is
    // what catches a suite whose signing became non-deterministic between versions.
    if v.expect_valid {
        let sk_bytes = unhex(&v.name, &v.signing_key)?;
        if !sk_bytes.is_empty() {
            let sk =
                Sig::<S>::decode_sk(&sk_bytes).map_err(|_| KatError::BadKey(v.name.clone()))?;
            let sign_kind = kind_by_name(&v.sign_kind)
                .ok_or_else(|| KatError::UnknownKind(v.sign_kind.clone()))?;
            let sign_ctx = DomainCtx::new(sign_kind, S::SUITE_ID, &v.sign_product);
            let regenerated =
                Sig::<S>::sign(&sk, sign_ctx, &msg).map_err(|_| KatError::Mismatch {
                    name: v.name.clone(),
                    detail: String::from("re-signing failed"),
                })?;
            if regenerated != sig {
                return Err(KatError::Mismatch {
                    name: v.name.clone(),
                    detail: String::from("re-signing produced different bytes"),
                });
            }
        }
    }
    Ok(())
}

fn replay_kdf<S: CryptoSuite>(v: &KdfVector) -> Result<(), KatError> {
    use copylocker_suite::KeyDerivation;
    type Kdf<S> = <S as CryptoSuite>::Kdf;

    let salt = unhex(&v.name, &v.salt)?;
    let ikm = unhex(&v.name, &v.ikm)?;
    let parts: Vec<Vec<u8>> = v
        .info
        .iter()
        .map(|p| unhex(&v.name, p))
        .collect::<Result<_, _>>()?;
    let refs: Vec<&[u8]> = parts.iter().map(Vec::as_slice).collect();

    let got = Kdf::<S>::derive_from(&salt, &ikm, &refs).map_err(|_| KatError::Mismatch {
        name: v.name.clone(),
        detail: String::from("derivation failed"),
    })?;
    let want = unhex(&v.name, &v.expect)?;
    if got.as_slice() != want.as_slice() {
        return Err(KatError::Mismatch {
            name: v.name.clone(),
            detail: alloc::format!("expected {}, got {}", v.expect, hex::encode(got.as_slice())),
        });
    }
    Ok(())
}

fn replay_fingerprint<S: CryptoSuite>(v: &FingerprintVector) -> Result<(), KatError> {
    use copylocker_suite::device::{DeviceAttrs, FingerprintScheme as _};
    type Fpr<S> = <S as CryptoSuite>::Fpr;

    let salt = unhex(&v.name, &v.salt)?;
    let mut attrs = DeviceAttrs::new();
    for (k, spec) in &v.attrs {
        attrs.insert(k.clone(), spec.to_attr());
    }
    let got = Fpr::<S>::compute(&salt, &attrs);
    let want = unhex(&v.name, &v.expect)?;
    if got.as_bytes() != want.as_slice() {
        return Err(KatError::Mismatch {
            name: v.name.clone(),
            detail: alloc::format!("expected {}, got {}", v.expect, hex::encode(got.as_bytes())),
        });
    }
    Ok(())
}

/// Generate a vector file for a suite.
///
/// Used by `copylocker-cli kat generate` to refresh `vectors/`. Regenerating existing vectors is
/// a **breaking protocol change** — if the bytes move, credentials signed by the old code no
/// longer verify. CI compares generated output against the committed file for exactly that
/// reason.
#[must_use]
pub fn generate<S: CryptoSuite>() -> VectorFile {
    use copylocker_suite::device::{AttrValue, DeviceAttrs, FingerprintScheme as _};
    use copylocker_suite::KeyDerivation;
    type Sig<S> = <S as CryptoSuite>::Sig;
    type Kdf<S> = <S as CryptoSuite>::Kdf;
    type Fpr<S> = <S as CryptoSuite>::Fpr;

    let mut rng = crate::TestRng::new(0x4B41_5430);
    let (sk, vk) = Sig::<S>::generate(&mut rng);
    let sk_hex = hex::encode(Sig::<S>::encode_sk(&sk));
    let vk_hex = hex::encode(Sig::<S>::encode_vk(&vk));
    let msg = b"copylocker kat message";
    let msg_hex = hex::encode(msg);

    let mut signatures = Vec::new();

    // Positive: one vector per artifact kind, so every domain is pinned.
    for kind in ArtifactKind::ALL {
        let ctx = DomainCtx::new(kind, S::SUITE_ID, "kat-product");
        let Ok(sig) = Sig::<S>::sign(&sk, ctx, msg) else {
            continue;
        };
        signatures.push(SignatureVector {
            name: alloc::format!("positive/{}", kind.ctx_name()),
            signing_key: sk_hex.clone(),
            verifying_key: vk_hex.clone(),
            sign_kind: String::from(kind.ctx_name()),
            verify_kind: String::from(kind.ctx_name()),
            sign_product: String::from("kat-product"),
            verify_product: String::from("kat-product"),
            message: msg_hex.clone(),
            signature: hex::encode(sig.as_bytes()),
            expect_valid: true,
        });
    }

    let base_ctx = DomainCtx::new(ArtifactKind::MachineCred, S::SUITE_ID, "kat-product");
    if let Ok(sig) = Sig::<S>::sign(&sk, base_ctx, msg) {
        // Negative: cross-domain replay.
        signatures.push(SignatureVector {
            name: String::from("negative/cross-domain-replay"),
            signing_key: String::new(),
            verifying_key: vk_hex.clone(),
            sign_kind: String::from("machine-cred"),
            verify_kind: String::from("kill-order"),
            sign_product: String::from("kat-product"),
            verify_product: String::from("kat-product"),
            message: msg_hex.clone(),
            signature: hex::encode(sig.as_bytes()),
            expect_valid: false,
        });

        // Negative: cross-product replay.
        signatures.push(SignatureVector {
            name: String::from("negative/cross-product-replay"),
            signing_key: String::new(),
            verifying_key: vk_hex.clone(),
            sign_kind: String::from("machine-cred"),
            verify_kind: String::from("machine-cred"),
            sign_product: String::from("kat-product"),
            verify_product: String::from("other-product"),
            message: msg_hex.clone(),
            signature: hex::encode(sig.as_bytes()),
            expect_valid: false,
        });

        // Negative: tampered message.
        let mut tampered_msg = msg.to_vec();
        if let Some(b) = tampered_msg.first_mut() {
            *b ^= 0x01;
        }
        signatures.push(SignatureVector {
            name: String::from("negative/tampered-message"),
            signing_key: String::new(),
            verifying_key: vk_hex.clone(),
            sign_kind: String::from("machine-cred"),
            verify_kind: String::from("machine-cred"),
            sign_product: String::from("kat-product"),
            verify_product: String::from("kat-product"),
            message: hex::encode(&tampered_msg),
            signature: hex::encode(sig.as_bytes()),
            expect_valid: false,
        });

        // Negative: corrupt the first component, which for a hybrid is the PQ half. This is the
        // component-stripping vector the spec requires.
        let mut stripped = sig.as_bytes().to_vec();
        if stripped.len() > 8 {
            // Skip the 4-byte length prefix; corrupt the component body itself.
            #[allow(clippy::indexing_slicing)]
            {
                stripped[4] ^= 0xff;
            }
        }
        signatures.push(SignatureVector {
            name: String::from("negative/first-component-forged"),
            signing_key: String::new(),
            verifying_key: vk_hex.clone(),
            sign_kind: String::from("machine-cred"),
            verify_kind: String::from("machine-cred"),
            sign_product: String::from("kat-product"),
            verify_product: String::from("kat-product"),
            message: msg_hex.clone(),
            signature: hex::encode(&stripped),
            expect_valid: false,
        });

        // Negative: corrupt the trailing component, the classical half.
        let mut tail = sig.as_bytes().to_vec();
        if let Some(b) = tail.last_mut() {
            *b ^= 0xff;
        }
        signatures.push(SignatureVector {
            name: String::from("negative/last-component-forged"),
            signing_key: String::new(),
            verifying_key: vk_hex.clone(),
            sign_kind: String::from("machine-cred"),
            verify_kind: String::from("machine-cred"),
            sign_product: String::from("kat-product"),
            verify_product: String::from("kat-product"),
            message: msg_hex.clone(),
            signature: hex::encode(&tail),
            expect_valid: false,
        });

        // Negative: truncated signature.
        signatures.push(SignatureVector {
            name: String::from("negative/truncated"),
            signing_key: String::new(),
            verifying_key: vk_hex.clone(),
            sign_kind: String::from("machine-cred"),
            verify_kind: String::from("machine-cred"),
            sign_product: String::from("kat-product"),
            verify_product: String::from("kat-product"),
            message: msg_hex.clone(),
            signature: hex::encode(sig.as_bytes().get(..sig.len() / 2).unwrap_or_default()),
            expect_valid: false,
        });
    }

    // X-Wing vectors pin both the wire encoding and implicit-rejection behaviour.
    type Kem<S> = <S as CryptoSuite>::Kem;
    let mut kem_rng = crate::TestRng::new(0x4B45_4D30);
    let (dk, ek) = Kem::<S>::keygen(&mut kem_rng);
    let mut kem = Vec::new();
    if let Ok((ct, shared_secret)) = Kem::<S>::encap(&ek, &mut kem_rng) {
        let dk_hex = hex::encode(Kem::<S>::encode_dk(&dk));
        let ek_hex = hex::encode(Kem::<S>::encode_ek(&ek));
        let ct_hex = hex::encode(ct.as_bytes());
        let secret_hex = hex::encode(shared_secret.expose());
        kem.push(KemVector {
            name: String::from("positive/encap-decap"),
            decapsulation_key: dk_hex.clone(),
            encapsulation_key: ek_hex.clone(),
            ciphertext: ct_hex.clone(),
            shared_secret: secret_hex.clone(),
            expect_valid: true,
        });

        let mut tampered = ct.as_bytes().to_vec();
        if let Some(first) = tampered.first_mut() {
            *first ^= 0x01;
        }
        kem.push(KemVector {
            name: String::from("negative/tampered-ciphertext"),
            decapsulation_key: dk_hex,
            encapsulation_key: ek_hex,
            ciphertext: hex::encode(tampered),
            shared_secret: secret_hex.clone(),
            expect_valid: false,
        });

        let (other_dk, other_ek) = Kem::<S>::keygen(&mut kem_rng);
        kem.push(KemVector {
            name: String::from("negative/wrong-device-key"),
            decapsulation_key: hex::encode(Kem::<S>::encode_dk(&other_dk)),
            encapsulation_key: hex::encode(Kem::<S>::encode_ek(&other_ek)),
            ciphertext: ct_hex,
            shared_secret: secret_hex,
            expect_valid: false,
        });
    }

    // Fixed-nonce vectors make the AEAD bytes portable across targets and versions.
    type Aead<S> = <S as CryptoSuite>::Aead;
    let key = alloc::vec![0x11; Aead::<S>::KEY_LEN];
    let nonce = alloc::vec![0x22; Aead::<S>::NONCE_LEN];
    let aad = b"copylocker kat aad";
    let plaintext = b"copylocker kat plaintext";
    let mut aead = Vec::new();
    if let Ok(ciphertext) = Aead::<S>::seal(&key, &nonce, aad, plaintext) {
        let key_hex = hex::encode(&key);
        let nonce_hex = hex::encode(&nonce);
        let aad_hex = hex::encode(aad);
        let plaintext_hex = hex::encode(plaintext);
        let ciphertext_hex = hex::encode(&ciphertext);
        aead.push(AeadVector {
            name: String::from("positive/seal-open"),
            key: key_hex.clone(),
            nonce: nonce_hex.clone(),
            aad: aad_hex.clone(),
            plaintext: plaintext_hex.clone(),
            ciphertext: ciphertext_hex.clone(),
            expect_valid: true,
        });
        aead.push(AeadVector {
            name: String::from("negative/wrong-aad"),
            key: key_hex.clone(),
            nonce: nonce_hex.clone(),
            aad: hex::encode(b"other aad"),
            plaintext: plaintext_hex.clone(),
            ciphertext: ciphertext_hex.clone(),
            expect_valid: false,
        });
        aead.push(AeadVector {
            name: String::from("negative/wrong-key"),
            key: hex::encode(alloc::vec![0x12; Aead::<S>::KEY_LEN]),
            nonce: nonce_hex,
            aad: aad_hex,
            plaintext: plaintext_hex,
            ciphertext: ciphertext_hex,
            expect_valid: false,
        });
        let mut tampered = ciphertext;
        if let Some(last) = tampered.last_mut() {
            *last ^= 0x01;
        }
        aead.push(AeadVector {
            name: String::from("negative/tampered-tag"),
            key: key_hex,
            nonce: hex::encode(&nonce),
            aad: hex::encode(aad),
            plaintext: hex::encode(plaintext),
            ciphertext: hex::encode(tampered),
            expect_valid: false,
        });
    }

    // Protocol-specific AEAD vectors pin the exact KDF and canonical AAD used by `sealed_cs`
    // and wrapped asset KEKs, not merely the underlying primitive.
    let credential_fingerprint = Fingerprint::from_vec(alloc::vec![0x55; 32]);
    let credential_kem_ct = alloc::vec![0x66; 64];
    let credential_offline_nonce = [0x77; 32];
    let credential_context = CredentialSealContext {
        proto_ver: S::PROTO_VER,
        suite_id: S::SUITE_ID,
        product_id: "kat-product",
        license_id: LicenseId([0x11; 16]),
        machine_id: MachineId([0x22; 16]),
        fingerprint: &credential_fingerprint,
        kem_ct: &credential_kem_ct,
        offline_nonce: &credential_offline_nonce,
        epoch_id: EpochId([0x42; 8]),
        variant_id: 7,
    };
    let credential_shared = SharedSecret::new([0x88; 32]);
    let credential_nonce = alloc::vec![0x99; Aead::<S>::NONCE_LEN];
    let credential_plaintext = [0xaa; 32];
    if let Ok(credential_key) = credential_wrap_key::<S>(&credential_shared, &credential_context) {
        let credential_aad = credential_context.aad();
        if let Ok(ciphertext) = Aead::<S>::seal(
            credential_key.expose(),
            &credential_nonce,
            &credential_aad,
            &credential_plaintext,
        ) {
            aead.push(AeadVector {
                name: String::from("positive/credential-secret-seal-v1"),
                key: hex::encode(credential_key.expose()),
                nonce: hex::encode(&credential_nonce),
                aad: hex::encode(&credential_aad),
                plaintext: hex::encode(credential_plaintext),
                ciphertext: hex::encode(ciphertext),
                expect_valid: true,
            });
        }
    }

    let variant_id = 7u64.to_be_bytes();
    let variant_const = [0xbb; 32];
    let feature_session_root = [0xcc; 32];
    let feature_info = [
        &b"kat-product"[..],
        &variant_id[..],
        &variant_const[..],
        &b"export.pdf"[..],
    ];
    if let Ok(feature_key) =
        Kdf::<S>::derive_from(b"copylocker/fk/v1", &feature_session_root, &feature_info)
    {
        let session_nonce = [0xdd; 32];
        let kek_context = KekWrapContext {
            proto_ver: S::PROTO_VER,
            suite_id: S::SUITE_ID,
            product_id: "kat-product",
            license_id: LicenseId([0x11; 16]),
            machine_id: MachineId([0x22; 16]),
            epoch_id: EpochId([0x42; 8]),
            variant_id: 7,
            feature_id: "export.pdf",
            kind: KekWrapKind::Offline,
            session_nonce: &session_nonce,
        };
        let kek_nonce = alloc::vec![0xee; Aead::<S>::NONCE_LEN];
        let kek_plaintext = [0xf0; 32];
        let kek_aad = kek_context.aad();
        if let Ok(ciphertext) =
            Aead::<S>::seal(feature_key.as_slice(), &kek_nonce, &kek_aad, &kek_plaintext)
        {
            aead.push(AeadVector {
                name: String::from("positive/offline-kek-wrap-v1"),
                key: hex::encode(feature_key.as_slice()),
                nonce: hex::encode(&kek_nonce),
                aad: hex::encode(&kek_aad),
                plaintext: hex::encode(kek_plaintext),
                ciphertext: hex::encode(ciphertext),
                expect_valid: true,
            });
        }
    }

    // KDF vectors covering the derivations in the key hierarchy.
    let mut kdf = Vec::new();
    let session_epoch = [0x42; 8];
    let session_build = b"build-kat";
    let session_module = [0x51; 32];
    for (name, salt, ikm, info) in [
        (
            "bind",
            &b"copylocker/bind/v1"[..],
            &[0x11u8; 32][..],
            alloc::vec![&b"fingerprint"[..], &b"env-digest"[..]],
        ),
        (
            "session-root",
            &b"copylocker/sr/v1"[..],
            &[0x22u8; 32][..],
            alloc::vec![
                &b"server-nonce"[..],
                &session_epoch[..],
                &session_build[..],
                &session_module[..],
            ],
        ),
        (
            "feature-key",
            &b"copylocker/fk/v1"[..],
            &feature_session_root[..],
            alloc::vec![
                &b"kat-product"[..],
                &variant_id[..],
                &variant_const[..],
                &b"export.pdf"[..],
            ],
        ),
        (
            "credential-wrap-key",
            CREDENTIAL_WRAP_SALT,
            &credential_shared.expose()[..],
            alloc::vec![
                &S::SUITE_ID.as_bytes()[..],
                &b"kat-product"[..],
                &LicenseId([0x11; 16]).as_bytes()[..],
                &MachineId([0x22; 16]).as_bytes()[..],
            ],
        ),
    ] {
        if let Ok(out) = Kdf::<S>::derive_from(salt, ikm, &info) {
            kdf.push(KdfVector {
                name: String::from(name),
                salt: hex::encode(salt),
                ikm: hex::encode(ikm),
                info: info.iter().map(hex::encode).collect(),
                expect: hex::encode(out.as_slice()),
            });
        }
    }

    // Fingerprint vector exercising every attribute variant, including explicit absence.
    let specs: Vec<(String, AttrSpec)> = alloc::vec![
        (
            String::from("machine_guid"),
            AttrSpec::Text {
                value: String::from("A1B2-C3D4")
            }
        ),
        (
            String::from("mac_addrs"),
            AttrSpec::Set {
                values: alloc::vec![String::from("aa:bb"), String::from("cc:dd")]
            }
        ),
        (
            String::from("hardware_concurrency"),
            AttrSpec::Int { value: 8 }
        ),
        (String::from("board_serial"), AttrSpec::Absent),
    ];
    let mut attrs = DeviceAttrs::new();
    for (k, spec) in &specs {
        attrs.insert(k.clone(), spec.to_attr());
    }
    let _ = AttrValue::Absent; // variant referenced above via AttrSpec
    let fingerprints = alloc::vec![FingerprintVector {
        name: String::from("all-variants"),
        salt: hex::encode(b"kat-vendor-salt"),
        attrs: specs,
        expect: hex::encode(Fpr::<S>::compute(b"kat-vendor-salt", &attrs).as_bytes()),
    }];

    let (artifacts, chains) = crate::protocol_kat::generate::<S>();

    VectorFile {
        suite_id: alloc::format!("{}", S::SUITE_ID),
        suite_name: String::from(S::NAME),
        format: 2,
        signatures,
        kem,
        aead,
        kdf,
        fingerprints,
        artifacts,
        chains,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use copylocker_suite_std::ClStd1;

    #[test]
    fn generated_vectors_replay_cleanly() {
        let file = generate::<ClStd1>();
        let n = replay::<ClStd1>(&file).expect("generated vectors must replay");
        assert_eq!(
            n,
            file.signatures.len()
                + file.kem.len()
                + file.aead.len()
                + file.kdf.len()
                + file.fingerprints.len()
                + file.artifacts.len()
                + file.chains.len()
        );
    }

    #[test]
    fn generation_covers_every_artifact_kind_and_the_required_negatives() {
        let file = generate::<ClStd1>();
        for kind in ArtifactKind::ALL {
            let want = alloc::format!("positive/{}", kind.ctx_name());
            assert!(
                file.signatures.iter().any(|s| s.name == want),
                "missing positive vector for {}",
                kind.ctx_name()
            );
        }
        for required in [
            "negative/cross-domain-replay",
            "negative/cross-product-replay",
            "negative/tampered-message",
            "negative/first-component-forged",
            "negative/last-component-forged",
            "negative/truncated",
        ] {
            assert!(
                file.signatures.iter().any(|s| s.name == required),
                "missing {required}"
            );
        }
        assert!(file.signatures.iter().filter(|s| !s.expect_valid).count() >= 6);
        assert!(file.kem.iter().any(|v| v.name == "positive/encap-decap"));
        assert!(file
            .kem
            .iter()
            .any(|v| v.name == "negative/wrong-device-key"));
        assert!(file.aead.iter().any(|v| v.name == "positive/seal-open"));
        assert!(file.aead.iter().any(|v| v.name == "negative/tampered-tag"));
        for kind in ArtifactKind::ALL {
            let want = alloc::format!("canonical/{}", kind.ctx_name());
            assert!(
                file.artifacts.iter().any(|v| v.name == want),
                "missing canonical artifact vector for {}",
                kind.ctx_name()
            );
        }
        assert!(file
            .chains
            .iter()
            .any(|v| v.name == "positive/root-epoch-machine-cred"));
        assert!(file
            .chains
            .iter()
            .any(|v| v.name == "negative/unpinned-root" && !v.expect_valid));
        assert!(file
            .chains
            .iter()
            .any(|v| v.name == "negative/expired-epoch" && !v.expect_valid));
    }

    #[test]
    fn vectors_survive_json_serialisation() {
        let file = generate::<ClStd1>();
        let json = serde_json::to_string_pretty(&file).unwrap();
        let back: VectorFile = serde_json::from_str(&json).unwrap();
        assert!(replay::<ClStd1>(&back).is_ok());
    }

    #[test]
    fn a_corrupted_positive_vector_is_caught() {
        // The harness must actually notice when the answers move.
        let mut file = generate::<ClStd1>();
        let v = file
            .signatures
            .iter_mut()
            .find(|s| s.expect_valid)
            .expect("a positive vector exists");
        v.signature.replace_range(0..2, "ff");
        assert!(matches!(
            replay::<ClStd1>(&file),
            Err(KatError::Mismatch { .. })
        ));
    }

    #[test]
    fn a_corrupted_kdf_vector_is_caught() {
        let mut file = generate::<ClStd1>();
        file.kdf[0].expect = hex::encode([0u8; 32]);
        assert!(matches!(
            replay::<ClStd1>(&file),
            Err(KatError::Mismatch { .. })
        ));
    }

    #[test]
    fn a_corrupted_fingerprint_vector_is_caught() {
        let mut file = generate::<ClStd1>();
        file.fingerprints[0].expect = hex::encode([0u8; 32]);
        assert!(matches!(
            replay::<ClStd1>(&file),
            Err(KatError::Mismatch { .. })
        ));
    }

    #[test]
    fn a_corrupted_artifact_vector_is_caught() {
        let mut file = generate::<ClStd1>();
        file.artifacts[0].canonical.replace_range(0..2, "ff");
        assert!(matches!(
            replay::<ClStd1>(&file),
            Err(KatError::Mismatch { .. })
        ));
    }

    #[test]
    fn a_corrupted_chain_vector_is_caught() {
        let mut file = generate::<ClStd1>();
        file.chains[0].artifact_envelope.replace_range(0..2, "ff");
        assert!(matches!(
            replay::<ClStd1>(&file),
            Err(KatError::Mismatch { .. })
        ));
    }

    #[test]
    fn a_vector_file_for_another_suite_is_refused() {
        let mut file = generate::<ClStd1>();
        file.suite_id = String::from("0x02000001");
        assert!(matches!(
            replay::<ClStd1>(&file),
            Err(KatError::SuiteMismatch { .. })
        ));
    }

    #[test]
    fn generation_is_reproducible() {
        // If this ever fails, the suite became non-deterministic and every committed vector
        // would need regenerating — which would break existing credentials.
        let a = serde_json::to_string(&generate::<ClStd1>()).unwrap();
        let b = serde_json::to_string(&generate::<ClStd1>()).unwrap();
        assert_eq!(a, b);
    }
}
