/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Native CopyLocker client held by the Electron main process. */
export declare class CopyLockerNative {
  /** Construct and restore a native client. */
  static create(config: NativeConfig): Promise<CopyLockerNative>
  /** Activate with a licence key. */
  activate(key: string): Promise<void>
  /** Release an online seat or erase a local OLK. */
  deactivate(): Promise<void>
  /** Advisory only; never gate product functionality on this value. */
  state(): NativeState
  /** Authenticate and decrypt a sealed asset off the JavaScript thread. */
  unseal(feature: string, data: Buffer): Promise<Buffer>
  /** Answer an opaque feature challenge off the JavaScript thread. */
  challenge(input: Buffer): Promise<Buffer>
  /** Create and persist a device-bound offline activation request. */
  offlineRequest(key: string): Promise<Buffer>
  /** Verify and install an offline activation response. */
  offlineImport(data: Buffer): Promise<void>
  /** Verify and install an armored Offline License Key bundle. */
  importOlk(data: string): Promise<void>
}

/** Compute the same non-boolean evidence digest used during client construction. */
export declare function collectEvidence(options: EvidenceOptions): Promise<Buffer>

/** Paths and fallback bytes used to collect Electron integrity evidence. */
export interface EvidenceOptions {
  /** Absolute path to the loaded `.node` file. */
  modulePath: string
  /** Absolute path to `app.asar`, when packaged. */
  asarPath?: string
  /** Embedded digest used only when local file collection is unavailable. */
  expectedModuleDigest: Buffer
}

/** Build-time client configuration passed from the Electron main process. */
export interface NativeConfig {
  serverUrl: string
  appId: string
  productId: string
  appVersion: string
  releaseId: string
  buildFingerprint: string
  currentRootKey: Buffer
  nextRootKey?: Buffer
  fingerprintSalt: Buffer
  variantId: number
  variantConst: Buffer
  evidence: EvidenceOptions
  allowUnboundOlk?: boolean
  allowInsecureLocalhost?: boolean
}

/** Advisory UI state. Productive access is available only through byte transformations. */
export interface NativeState {
  state: string
}
