/**
 * WASM export-name randomization tests (`40-web-sdk-wasm-ts.md §5`).
 *
 * The executable fixture is a minimal hand-encoded module plus a glue file
 * written in the exact style wasm-bindgen emits (`wasm = instance.exports`,
 * `wasm.<name>(...)` dot access, `wasm["<name>"]` bracket access,
 * `wasm.memory.buffer`). When the real `copylocker-wasm` build artifact is
 * present on disk (it is git-ignored — generated by the packages/web build),
 * an extra round-trip runs against it.
 */

import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { pathToFileURL, fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { bootGuard, decodeManifest, zeroExcludedRanges } from '@copylocker/guard'
import { resolveConfig } from '../src/config.js'
import { runPipeline, type BuildIdentity, type PipelineInput, type PipelineResult } from '../src/core.js'
import { sha256, toHex } from '../src/hash.js'
import {
  countGlueReferences,
  deriveExportName,
  deriveExportRenames,
  listWasmExports,
  randomizeExports,
  rewriteGlueReferences,
} from '../src/wasm-randomize.js'
import { makeLocalSigner, distFetch, withTempDir } from './helpers.js'

const SEED_A = 'aa'.repeat(32)
const SEED_B = 'bb'.repeat(32)

const IDENTITY: BuildIdentity = {
  buildFingerprint: 'clb-test-nogit-0123456789abcdef',
  builtAt: 1_754_600_000,
  kbuild: 'ab'.repeat(32),
  buildSeed: SEED_A,
}

// ---------------------------------------------------------------------------
// Synthetic wasm-bindgen-style fixture
// ---------------------------------------------------------------------------

function leb(value: number): number[] {
  const out: number[] = []
  let remaining = value
  do {
    let byte = remaining % 128
    remaining = Math.floor(remaining / 128)
    if (remaining > 0) byte |= 0x80
    out.push(byte)
  } while (remaining > 0)
  return out
}

function section(id: number, payload: number[]): number[] {
  return [id, ...leb(payload.length), ...payload]
}

function nameBytes(value: string): number[] {
  return [...leb(value.length), ...new TextEncoder().encode(value)]
}

/**
 * Exports: `memory` (stable), `demo_step`/`demo_new` (renameable) and `run`
 * (too short — kept). The custom `name` section repeats `demo_step`, which is
 * exactly the leak the rewriter must remove.
 */
function buildTestWasm(): Uint8Array {
  const typeSec = section(1, [1, 0x60, 2, 0x7f, 0x7f, 1, 0x7f]) // (i32, i32) -> i32
  const funcSec = section(3, [2, 0, 0])
  const memSec = section(5, [1, 0x00, 1])
  const exportSec = section(7, [
    4,
    ...nameBytes('memory'), 0x02, 0,
    ...nameBytes('demo_step'), 0x00, 0,
    ...nameBytes('demo_new'), 0x00, 1,
    ...nameBytes('run'), 0x00, 0,
  ])
  // local.get 0; local.get 1; i32.add; end
  const body = [0x00, 0x20, 0x00, 0x20, 0x01, 0x6a, 0x0b]
  const codeSec = section(10, [2, ...leb(body.length), ...body, ...leb(body.length), ...body])
  const nameSec = section(0, [...nameBytes('name'), ...nameBytes('demo_step'), 0xde, 0xad])
  return new Uint8Array([
    0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
    ...typeSec, ...funcSec, ...memSec, ...exportSec, ...codeSec, ...nameSec,
  ])
}

/** Glue in the shape wasm-bindgen generates (dot + bracket + memory access). */
function testGlue(): string {
  return `
let wasm
function finalize(instance) { wasm = instance.exports; return wasm }
export function initSync(bytes) {
  return finalize(new WebAssembly.Instance(new WebAssembly.Module(bytes), {}))
}
let cached
function memory0() {
  if (!cached) cached = new Uint8Array(wasm.memory.buffer)
  return cached
}
export class DemoSession {
  // calls demo_step, the semantic entry point
  step(a, b) {
    const ret = wasm.demo_step(a, b)
    memory0()[0] = ret & 0xff
    return ret
  }
  alloc(n) { return wasm["demo_new"](n, 0) }
}
export const label = "demo_step" // a plain string literal — must survive
`
}

interface GlueModule {
  initSync(bytes: Uint8Array): WebAssembly.Exports
  DemoSession: new () => { step(a: number, b: number): number; alloc(n: number): number }
  label: string
}

async function importGlue(dir: string, text: string, tag: string): Promise<GlueModule> {
  const file = join(dir, `glue-${tag}.mjs`)
  await writeFile(file, text)
  return (await import(pathToFileURL(file).href)) as GlueModule
}

/** Final on-disk bytes for every covered output after patching. */
function finalFiles(inputs: PipelineInput[], result: PipelineResult): Map<string, Uint8Array> {
  const files = new Map<string, Uint8Array>()
  const encoder = new TextEncoder()
  for (const input of inputs) {
    const patchedText = result.patchedTexts.get(input.fileName)
    const patchedAsset = result.patchedAssets.get(input.fileName)
    if (patchedText !== undefined) files.set(input.fileName, encoder.encode(patchedText))
    else if (patchedAsset !== undefined) files.set(input.fileName, patchedAsset)
    else if (input.text !== undefined) files.set(input.fileName, encoder.encode(input.text))
    else files.set(input.fileName, input.bytes as Uint8Array)
  }
  for (const [name, bytes] of result.extraAssets) files.set(name, bytes)
  return files
}

// ---------------------------------------------------------------------------
// Unit: binary rewriter
// ---------------------------------------------------------------------------

describe('wasm export randomization: binary rewriter', () => {
  it('renames renameable exports, keeps stable ones, strips the name section', async () => {
    const original = buildTestWasm()
    const { bytes, renames } = randomizeExports(original, SEED_A)

    expect([...renames.keys()].sort()).toEqual(['demo_new', 'demo_step'])
    for (const newName of renames.values()) expect(newName).toMatch(/^__cl_[0-9a-f]{16}$/)

    const after = listWasmExports(bytes).map((entry) => entry.name).sort()
    expect(after).toEqual(['memory', 'run', ...[...renames.values()]].sort())

    // the rewritten module still compiles and behaves identically
    const { instance } = await WebAssembly.instantiate(bytes, {})
    const exports = instance.exports as Record<string, (...args: number[]) => number>
    const step = exports[renames.get('demo_step') as string] as (...args: number[]) => number
    expect(step(2, 3)).toBe(5)
    expect(exports['demo_step']).toBeUndefined()
    expect(exports['run']?.(2, 3)).toBe(5)
    expect(exports['memory']).toBeInstanceOf(WebAssembly.Memory)

    // tamper resistance: original names are not findable in the emitted bytes
    // (the custom name section, which repeated 'demo_step', was stripped)
    const haystack = Buffer.from(bytes)
    expect(haystack.includes(Buffer.from('demo_step'))).toBe(false)
    expect(haystack.includes(Buffer.from('demo_new'))).toBe(false)
    expect(haystack.includes(Buffer.from('memory'))).toBe(true)
  })

  it('is deterministic per seed and distinct across seeds', () => {
    const original = buildTestWasm()
    const first = randomizeExports(original, SEED_A)
    const second = randomizeExports(original, SEED_A)
    const other = randomizeExports(original, SEED_B)

    expect(toHex(first.bytes)).toBe(toHex(second.bytes))
    expect(first.renames.get('demo_step')).toBe(second.renames.get('demo_step'))
    expect(first.renames.get('demo_step')).not.toBe(other.renames.get('demo_step'))
    expect(deriveExportName(SEED_A, 'demo_step')).toBe(first.renames.get('demo_step'))
  })

  it('never derives a name that collides with an existing export', () => {
    const renames = deriveExportRenames(SEED_A, ['demo_step', deriveExportName(SEED_A, 'demo_new')])
    expect(renames.get('demo_new')).not.toBe(deriveExportName(SEED_A, 'demo_new'))
    expect(new Set(renames.values()).size).toBe(2)
  })
})

// ---------------------------------------------------------------------------
// Unit: glue rewrite
// ---------------------------------------------------------------------------

describe('wasm export randomization: glue rewrite', () => {
  it('rewrites dot and bracket accesses, leaves strings and stable names alone', () => {
    const glue = testGlue()
    const renames = new Map([
      ['demo_step', '__cl_aaaa'],
      ['demo_new', '__cl_bbbb'],
    ])
    expect(countGlueReferences(glue, renames.keys())).toBe(2)

    const rewritten = rewriteGlueReferences(glue, renames)
    expect(rewritten).toContain('wasm.__cl_aaaa(a, b)')
    expect(rewritten).toContain('wasm["__cl_bbbb"](n, 0)')
    expect(rewritten).toContain('wasm.memory.buffer') // stable export untouched
    expect(rewritten).toContain('"demo_step"') // string literal untouched
    expect(rewritten).not.toContain('.demo_step')
    expect(rewritten).not.toContain('["demo_new"]')
    expect(countGlueReferences(rewritten, renames.keys())).toBe(0)
  })

  it('matches property accesses even when the exports variable is renamed (minified)', () => {
    const minified = 'const n=t.exports;function e(r,o){return n.demo_step(r,o)}'
    const rewritten = rewriteGlueReferences(minified, new Map([['demo_step', '__cl_x1']]))
    expect(rewritten).toContain('n.__cl_x1(r,o)')
    expect(rewritten).not.toContain('demo_step')
  })
})

// ---------------------------------------------------------------------------
// Round-trip: rewritten wasm + rewritten glue still executes
// ---------------------------------------------------------------------------

describe('wasm export randomization: execution round-trip', () => {
  it('synthetic wasm-bindgen-style fixture behaves identically after renaming', async () => {
    await withTempDir(async (dir) => {
      const wasmBytes = buildTestWasm()
      const { bytes: renamedBytes, renames } = randomizeExports(wasmBytes, SEED_A)
      const renamedGlue = rewriteGlueReferences(testGlue(), renames)

      const original = await importGlue(dir, testGlue(), 'original')
      const renamed = await importGlue(dir, renamedGlue, 'renamed')

      const originalExports = original.initSync(wasmBytes)
      const renamedExports = renamed.initSync(renamedBytes)

      const a = new original.DemoSession()
      const b = new renamed.DemoSession()
      expect(b.step(20, 22)).toBe(a.step(20, 22))
      expect(b.alloc(7)).toBe(a.alloc(7))
      expect(renamed.label).toBe(original.label)

      // the exports surface really changed underneath the working glue
      const renamedName = renames.get('demo_step') as string
      expect(typeof renamedExports[renamedName]).toBe('function')
      expect(renamedExports['demo_step']).toBeUndefined()
      expect(typeof originalExports['demo_step']).toBe('function')
    })
  })

  const here = dirname(fileURLToPath(import.meta.url))
  const realWasm = join(here, '..', '..', 'web', 'src', 'wasm', 'copylocker_wasm_bg.wasm')
  const realGlue = join(here, '..', '..', 'web', 'src', 'wasm', 'copylocker_wasm.js')
  const hasRealArtifact = existsSync(realWasm) && existsSync(realGlue)

  // The real artifact is git-ignored (built by packages/web); run locally
  // whenever it is on disk, skip cleanly in fresh checkouts/CI.
  it.runIf(hasRealArtifact)(
    'real copylocker-wasm artifact: renamed wasm + glue initialize and behave identically',
    async () => {
      await withTempDir(async (dir) => {
        const wasmBytes = new Uint8Array(await readFile(realWasm))
        const glueText = await readFile(realGlue, 'utf8')
        const { bytes: renamedBytes, renames } = randomizeExports(wasmBytes, SEED_A)

        // every export except the stable `memory` is renamed
        const originalNames = listWasmExports(wasmBytes).map((entry) => entry.name)
        expect(originalNames).toContain('clsession_step')
        expect(renames.size).toBe(originalNames.length - 1)
        expect(renames.has('memory')).toBe(false)

        const renamedGlueText = rewriteGlueReferences(glueText, renames)
        expect(renamedGlueText).not.toContain('.clsession_step')
        expect(Buffer.from(renamedBytes).includes(Buffer.from('clsession_step'))).toBe(false)

        interface RealGlue {
          initSync(module: { module: Uint8Array }): WebAssembly.Exports
          ClSession: new (cfg: Uint8Array) => unknown
        }
        const load = async (text: string, tag: string): Promise<RealGlue> => {
          const file = join(dir, `glue-${tag}.mjs`)
          await writeFile(file, text)
          return (await import(pathToFileURL(file).href)) as RealGlue
        }

        // bad-CBOR construction must fail IDENTICALLY on both builds — any
        // glue/wasm mismatch would surface as a different (JS-level) error
        const attempt = (mod: RealGlue, bytes: Uint8Array): unknown => {
          const exports = mod.initSync({ module: bytes })
          try {
            new mod.ClSession(new Uint8Array([0xa0]))
            return { exports, threw: false, error: null }
          } catch (error) {
            return { exports, threw: true, error: String(error) }
          }
        }
        const original = attempt(await load(glueText, 'original'), wasmBytes)
        const renamed = attempt(await load(renamedGlueText, 'renamed'), renamedBytes)

        expect(renamed.threw).toBe(original.threw)
        expect(renamed.error).toBe(original.error)
        const renamedStep = (renamed.exports as Record<string, unknown>)[
          renames.get('clsession_step') as string
        ]
        expect(typeof renamedStep).toBe('function')
        expect((renamed.exports as Record<string, unknown>)['clsession_step']).toBeUndefined()
      })
    },
    30_000,
  )
})

// ---------------------------------------------------------------------------
// Pipeline integration
// ---------------------------------------------------------------------------

function wasmInputs(glueText: string, wasmBytes: Uint8Array): PipelineInput[] {
  return [
    { fileName: 'assets/index-aaa.js', kind: 'chunk', isEntry: true, text: glueText },
    {
      fileName: 'assets/chunk-bbb.js',
      kind: 'chunk',
      isEntry: false,
      // decoy: generic `.memory` / `.run` accesses that must NOT be rewritten
      text: 'export function peek(o){ return o.memory ? o.memory.view : o.run() }\n',
    },
    { fileName: 'assets/copylocker_wasm_bg.wasm', kind: 'asset', isEntry: false, bytes: wasmBytes },
  ]
}

describe('pipeline: randomizeWasmExports', () => {
  it('renames wasm + glue before digests; manifest and runtime agree; decoys untouched', async () => {
    await withTempDir(async (dir) => {
      const { keyFile, publicKey } = await makeLocalSigner(dir)
      const config = resolveConfig({
        productId: 'test-app',
        signer: { kind: 'local', keyFile },
        randomizeWasmExports: true,
      })
      const inputs = wasmInputs(testGlue(), buildTestWasm())
      const result = await runPipeline(inputs, config, IDENTITY, { warn: () => {} })

      // the wasm asset is patched and the manifest digests the RENAMED bytes
      const patchedWasm = result.patchedAssets.get('assets/copylocker_wasm_bg.wasm')
      expect(patchedWasm).toBeDefined()
      const signed = decodeManifest(result.manifestBytes)
      const wasmEntry = signed.manifest.entries.get('assets/copylocker_wasm_bg.wasm')
      expect(toHex(wasmEntry?.digest as Uint8Array)).toBe(toHex(await sha256(patchedWasm as Uint8Array)))
      expect(wasmEntry?.excludedRanges).toEqual([])

      // the entry chunk is the glue: renamed references survive the prelude
      const stepName = deriveExportName(SEED_A, 'demo_step')
      const entryText = result.patchedTexts.get('assets/index-aaa.js') as string
      expect(entryText).toContain(`wasm.${stepName}(a, b)`)
      expect(entryText).not.toContain('.demo_step')

      // the decoy chunk was never classified as glue
      expect(result.patchedTexts.has('assets/chunk-bbb.js')).toBe(false)

      // tamper resistance: no original export name in any emitted byte stream
      expect(Buffer.from(patchedWasm as Uint8Array).includes(Buffer.from('demo_step'))).toBe(false)

      // runtime: bootGuard over the final bytes recomputes R == manifest.root
      const files = finalFiles(inputs, result)
      const { R, report } = await bootGuard({
        manifest: result.manifestBytes,
        rootPins: [publicKey],
        chunks: [
          { url: 'assets/index-aaa.js', pattern: 'assets/index-aaa.js' },
          { url: 'assets/chunk-bbb.js', pattern: 'assets/chunk-bbb.js' },
          { url: 'assets/copylocker_wasm_bg.wasm', pattern: 'assets/copylocker_wasm_bg.wasm' },
        ],
        strategy: 'sync',
        fetchImpl: distFetch(files),
      })
      expect(report.signature).toBe('verified')
      expect(report.entries.every((entry) => entry.status === 'ok')).toBe(true)
      expect(toHex(R)).toBe(toHex(signed.manifest.root))

      // and the zeroed-excludedRanges invariant holds for the entry chunk
      const entryBytes = files.get('assets/index-aaa.js') as Uint8Array
      const entryRecord = signed.manifest.entries.get('assets/index-aaa.js')
      const recomputed = await sha256(zeroExcludedRanges(entryBytes, entryRecord?.excludedRanges ?? []))
      expect(toHex(recomputed)).toBe(toHex(entryRecord?.digest as Uint8Array))
    })
  })

  it('same build seed → identical randomized output across pipeline runs', async () => {
    await withTempDir(async (dir) => {
      const { keyFile } = await makeLocalSigner(dir)
      const config = resolveConfig({
        productId: 'test-app',
        signer: { kind: 'local', keyFile },
        randomizeWasmExports: true,
      })
      const first = await runPipeline(wasmInputs(testGlue(), buildTestWasm()), config, IDENTITY, {
        warn: () => {},
      })
      const second = await runPipeline(wasmInputs(testGlue(), buildTestWasm()), config, IDENTITY, {
        warn: () => {},
      })
      expect(toHex(first.patchedAssets.get('assets/copylocker_wasm_bg.wasm') as Uint8Array)).toBe(
        toHex(second.patchedAssets.get('assets/copylocker_wasm_bg.wasm') as Uint8Array),
      )
    })
  })

  it('warns and leaves the wasm untouched when no covered chunk references its exports', async () => {
    await withTempDir(async (dir) => {
      const { keyFile } = await makeLocalSigner(dir)
      const config = resolveConfig({
        productId: 'test-app',
        signer: { kind: 'local', keyFile },
        randomizeWasmExports: true,
      })
      const wasm = buildTestWasm()
      const inputs: PipelineInput[] = [
        { fileName: 'assets/index-aaa.js', kind: 'chunk', isEntry: true, text: 'console.log(1)\n' },
        { fileName: 'assets/copylocker_wasm_bg.wasm', kind: 'asset', isEntry: false, bytes: wasm },
      ]
      const warnings: string[] = []
      const result = await runPipeline(inputs, config, IDENTITY, {
        warn: (message) => warnings.push(message),
      })
      expect(warnings.some((message) => message.includes('no covered chunk references'))).toBe(true)
      expect(result.patchedAssets.size).toBe(0)
      expect(inputs[1]?.bytes).toBe(wasm)
    })
  })

  it('warns when enabled but no covered .wasm asset exists', async () => {
    await withTempDir(async (dir) => {
      const { keyFile } = await makeLocalSigner(dir)
      const config = resolveConfig({
        productId: 'test-app',
        signer: { kind: 'local', keyFile },
        randomizeWasmExports: true,
      })
      const warnings: string[] = []
      await runPipeline(
        [
          { fileName: 'assets/index-aaa.js', kind: 'chunk', isEntry: true, text: 'console.log(1)\n' },
        ],
        config,
        IDENTITY,
        { warn: (message) => warnings.push(message) },
      )
      expect(warnings.some((message) => message.includes('no covered .wasm asset'))).toBe(true)
    })
  })

  it('fails closed when the build seed is missing', async () => {
    await withTempDir(async (dir) => {
      const { keyFile } = await makeLocalSigner(dir)
      const config = resolveConfig({
        productId: 'test-app',
        signer: { kind: 'local', keyFile },
        randomizeWasmExports: true,
      })
      const identity: BuildIdentity = { ...IDENTITY }
      delete identity.buildSeed
      await expect(
        runPipeline(wasmInputs(testGlue(), buildTestWasm()), config, identity, { warn: () => {} }),
      ).rejects.toThrow(/buildSeed/)
    })
  })
})
