// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Grant } from "./Grant";
import type { LimitMergePolicy } from "./LimitMergePolicy";

/**
 * The input to resolution (`licensing-model.md §2.1`).
 */
export type EntitlementSpec = { 
/**
 * Base tier.
 */
tier: string, 
/**
 * Groups included on top of the tier.
 */
extra_groups: Array<string>, 
/**
 * Add-on grants.
 */
grants: Array<Grant>, 
/**
 * Features explicitly removed. Rare, but enterprise contracts need it.
 */
excluded_features: Array<string>, 
/**
 * Final limit overrides, applied last.
 */
limit_overrides: { [key in string]: number }, 
/**
 * Per-key merge policies. Keys absent here use [`LimitMergePolicy::Max`].
 */
limit_merge: { [key in string]: LimitMergePolicy }, };
