// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubscriptionHint } from "./SubscriptionHint";
import type { VersionScope } from "./VersionScope";

/**
 * Flattened entitlements written into a `MachineCredential` and refreshed by a
 * `ValidationTicket` (`licensing-model.md §9`).
 *
 * Ordering matters: `features` is a sorted set and `limits` a sorted map so that the canonical
 * CBOR encoding — and therefore the signature — is reproducible.
 */
export type Entitlements = { 
/**
 * Fully expanded feature identifiers. No globs, no duplicates, sorted.
 */
features: Array<string>, 
/**
 * Numeric limits. Enforcement is the vendor application's responsibility; CopyLocker only
 * signs the numbers (`licensing-model.md §2.5`).
 */
limits: { [key in string]: number }, 
/**
 * Tier the user is on, for display.
 */
tier_id: string, 
/**
 * Human-readable tier label, for display.
 */
tier_label: string, 
/**
 * Catalog version this snapshot was resolved against, for dispute forensics.
 */
catalog_version: number, 
/**
 * Version scope, for client-side UX only. **Not** an enforcement point
 * (`licensing-model.md §4.2`).
 */
version_scope: VersionScope | null, 
/**
 * Subscription status hints for in-app messaging. Not a security decision.
 */
subscription_hint: SubscriptionHint | null, };
