// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the perpetual fallback's version cap is anchored.
 */
export type FallbackScopeAt = "earned_at" | "subscription_start";
