// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single atomic capability.
 */
export type Feature = { 
/**
 * Identifier. Convention is `<domain>.<capability>`, e.g. `export.pdf`.
 *
 * **Immutable once published.**
 */
id: string, 
/**
 * Display label.
 */
label: string, 
/**
 * Optional longer description.
 */
description?: string | null, 
/**
 * When this feature was deprecated. A deprecated feature still resolves — existing
 * credentials must keep working — but new tiers should not reference it.
 */
deprecated_at?: number | null, };
