// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMembers } from "./GroupMembers";

/**
 * A named, reusable set of features.
 */
export type FeatureGroup = { 
/**
 * Group identifier.
 */
id: string, 
/**
 * Display label.
 */
label: string, 
/**
 * Membership.
 */
members: GroupMembers, };
