// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrantTarget } from "./GrantTarget";

/**
 * An add-on purchase or manual grant, optionally with its own validity window.
 */
export type Grant = { 
/**
 * What is granted.
 */
target: GrantTarget, 
/**
 * Start of the grant, inclusive. `None` means "already started".
 */
valid_from: number | null, 
/**
 * End of the grant, exclusive. `None` means "follows the license".
 */
valid_until: number | null, 
/**
 * Order number or promotion code, for audit.
 */
source: string, 
/**
 * Limit overrides carried by this grant.
 */
limits: { [key in string]: number }, };
