// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a grant confers.
 */
export type GrantTarget = { "kind": "feature", 
/**
 * Feature identifier.
 */
id: string, } | { "kind": "group", 
/**
 * Group identifier.
 */
id: string, };
