// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a group contains.
 */
export type GroupMembers = { 
/**
 * Other groups included wholesale.
 */
includes: Array<string>, 
/**
 * Feature identifiers, optionally with a trailing `*` glob such as `export.*`.
 *
 * Globs are expanded **server-side during resolution**; the wildcard never reaches a
 * client, because a client that received `export.*` would grant itself features that do
 * not exist yet (`licensing-model.md §2.3`).
 */
features: Array<string>, };
