// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which collection tier a metric belongs to (`90-analytics-telemetry.md §1`).
 */
export type MetricTier = "T0" | "T1";
