// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricTier } from "./MetricTier";

/**
 * One metric's precise definition, as served by `/v1/admin/analytics/definitions`.
 *
 * `trusted` mirrors the tier: T0 metrics come from signed credential usage records,
 * T1 metrics are client self-reports (`90-analytics-telemetry.md §6`). The console must
 * never plot trusted and untrusted series on the same unlabelled graph.
 */
export type MetricDefinition = { 
/**
 * Stable metric identifier, e.g. `act.new`. **Immutable once published.**
 */
id: string, 
/**
 * Human-readable name.
 */
name: string, 
/**
 * Terse, precise definition text for the definitions endpoint.
 */
definition: string, 
/**
 * Collection tier.
 */
tier: MetricTier, 
/**
 * Whether the value derives from signed credential usage (T0) or a client self-report (T1).
 */
trusted: boolean, };
