// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enforcement mode (`protocol-spec.md §4`, field 14; axis five of the policy model).
 */
export type Mode = "offline_hybrid" | "enforced_online";
