// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an offline client does when its variant is superseded.
 */
export type OfflineUpgradePolicy = "require_online" | "preload_n" | "variant_stable";
