// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackScopeAt } from "./FallbackScopeAt";

/**
 * Terms under which a subscription converts to a perpetual licence
 * (`licensing-model.md §5`).
 */
export type PerpetualFallback = { 
/**
 * Consecutive paid months required.
 */
after_months: number, 
/**
 * What the resulting version cap is measured from.
 */
scope_at: FallbackScopeAt, };
