// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntitlementSpec } from "./EntitlementSpec";
import type { Mode } from "./Mode";
import type { RuntimeSpec } from "./RuntimeSpec";
import type { SeatSpec } from "./SeatSpec";
import type { Validity } from "./Validity";
import type { VersionScope } from "./VersionScope";

/**
 * A complete policy: one point in the five-axis space.
 */
export type Policy = { 
/**
 * Policy identifier.
 */
id: string, 
/**
 * Product this policy belongs to.
 */
product_id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Which preset generated it, for the console's UI.
 */
preset: string | null, 
/**
 * Axis one.
 */
entitlement: EntitlementSpec, 
/**
 * Axis two.
 */
validity: Validity, 
/**
 * Axis three.
 */
version_scope: VersionScope, 
/**
 * Axis four.
 */
seats: SeatSpec, 
/**
 * Axis five.
 */
mode: Mode, 
/**
 * Runtime tuning.
 */
runtime: RuntimeSpec, };
