// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

/**
 * Query-result metadata: where the numbers came from, how far off they can be, and how
 * many buckets k-anonymity hid (`90-analytics-telemetry.md §8`).
 */
export type QueryMeta = { 
/**
 * Computation path.
 */
source: Source, 
/**
 * Worst-case relative error in percent: `0.0` for exact, [`super::HLL_ERROR_PCT`] for HLL.
 */
error_pct: number, 
/**
 * Buckets suppressed by k-anonymity.
 */
suppressed_buckets: number, };
