// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfflineUpgradePolicy } from "./OfflineUpgradePolicy";
import type { VtSignature } from "./VtSignature";

/**
 * Runtime tuning that ends up in every credential.
 */
export type RuntimeSpec = { 
/**
 * How long a credential is good for before an online check is due.
 */
refresh_after_secs: number, 
/**
 * Extra offline time granted when the network is unavailable at refresh time.
 */
grace_secs: number, 
/**
 * Minimum fingerprint similarity, `0..=100`, for reusing an activation.
 */
fpr_tolerance: number, 
/**
 * Whether activation inside a virtual machine is permitted.
 */
allow_vm: boolean, 
/**
 * Whether offline licence keys may be issued at all.
 */
allow_olk: boolean, 
/**
 * Whether an offline licence key may omit a device binding.
 *
 * Defaults to `false`: an unbound key can be copied without limit, and there is no server
 * in the loop to notice (`protocol-spec.md §8`).
 */
allow_unbound_olk: boolean, 
/**
 * `fast` for per-request Ed25519, `pq` to force the hybrid on every ticket.
 */
vt_signature: VtSignature, 
/**
 * How offline clients handle a variant change.
 */
offline_upgrade_policy: OfflineUpgradePolicy, 
/**
 * How many variants of keys to pre-load under `preload_n`.
 */
preload_variants_n: number, 
/**
 * Whether raw device attributes may be reported, enabling tolerance matching.
 */
report_attrs: boolean, };
