// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis four: seats and transfers.
 */
export type SeatSpec = { 
/**
 * Concurrent activations allowed.
 */
seats: number, 
/**
 * Maximum machine transfers within the window, if capped.
 */
max_transfers: number | null, 
/**
 * Length of the transfer window in seconds.
 */
transfer_window_secs: number | null, 
/**
 * Heartbeat interval enabling zombie-seat recovery. `None` disables it.
 */
heartbeat_secs: number | null, };
