// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which computation path produced a distinct-count series.
 */
export type Source = "exact" | "hll";
