// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubscriptionState } from "./SubscriptionState";

/**
 * Subscription hints for in-app copy such as "update your payment method" or
 * "3 more months until you keep this version forever" (`licensing-model.md §9`).
 */
export type SubscriptionHint = { 
/**
 * Current lifecycle state.
 */
state: SubscriptionState, 
/**
 * End of the paid period, Unix seconds.
 */
current_period_end: number, 
/**
 * Consecutive paid months accumulated toward a perpetual fallback.
 */
fallback_progress_months: number | null, 
/**
 * Months required to earn the perpetual fallback.
 */
fallback_required_months: number | null, };
