// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a subscription, mirrored to the client for messaging only.
 */
export type SubscriptionState = "active" | "past_due" | "canceling" | "suspended";
