// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A purchasable tier.
 */
export type Tier = { 
/**
 * Tier identifier.
 */
id: string, 
/**
 * Display label.
 */
label: string, 
/**
 * Ordering rank, used to tell an upgrade from a downgrade.
 */
rank: number, 
/**
 * Groups this tier includes.
 */
groups: Array<string>, 
/**
 * Features included directly, bypassing groups.
 */
features: Array<string>, 
/**
 * Numeric limits. `-1` means unlimited.
 */
limits: { [key in string]: number }, 
/**
 * When this tier was archived, if it is no longer sold.
 */
archived_at?: number | null, };
