// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a trial is deduplicated against (`licensing-model.md §3.3`).
 */
export type TrialScope = "fingerprint" | "account" | "email";
