// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerpetualFallback } from "./PerpetualFallback";
import type { TrialScope } from "./TrialScope";

/**
 * Axis two: how long the licence lasts (`licensing-model.md §3`).
 */
export type Validity = { "kind": "perpetual" } | { "kind": "fixed_term", 
/**
 * Duration in seconds.
 */
duration_secs: number, } | { "kind": "subscription", 
/**
 * Billing period in seconds.
 */
period_secs: number, 
/**
 * Grace after a failed payment, during which the app keeps working.
 */
dunning_grace_secs: number, 
/**
 * Perpetual fallback terms, if offered.
 */
fallback: PerpetualFallback | null, } | { "kind": "trial", 
/**
 * Duration in seconds.
 */
duration_secs: number, 
/**
 * What a trial is counted against.
 */
once_per: TrialScope, 
/**
 * Maximum manual extension support may grant.
 */
extendable_by_secs: number | null, };
