// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which application versions a license covers (`licensing-model.md §4`).
 */
export type VersionScope = { "kind": "unlimited" } | { "kind": "semver_range", "value": string } | { "kind": "released_before", "value": number } | { "kind": "pinned", "value": Array<string> };
