// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which signature protects a validation ticket.
 */
export type VtSignature = "fast" | "pq";
